// Sidebar groups for the docs — mirrors the Vue DocsPage GROUPS. Each `id`
// matches a `<section id>` rendered by a section component. `radar` is omitted:
// the Svelte kit has no radar chart series (the `Radar` name is a background).
export type NavItem = { id: string; label: string }
export type NavGroup = { title: string; items: NavItem[] }

const FORM: NavItem[] = [
  { id: "switch", label: "Switch" },
  { id: "checkbox", label: "Checkbox" },
  { id: "slider", label: "Slider" },
  { id: "progress", label: "Progress" },
]
const FIELD: NavItem[] = [
  { id: "input", label: "Input" },
  { id: "textarea", label: "Textarea" },
  { id: "field", label: "Field" },
  { id: "fieldset", label: "Fieldset" },
  { id: "form", label: "Form" },
  { id: "number-field", label: "Number Field" },
  { id: "otp-field", label: "OTP Field" },
]
const SELECTION: NavItem[] = [
  { id: "select", label: "Select" },
  { id: "combobox", label: "Combobox" },
  { id: "autocomplete", label: "Autocomplete" },
  { id: "radio", label: "Radio" },
  { id: "checkbox-group", label: "Checkbox Group" },
  { id: "toggle", label: "Toggle" },
  { id: "toggle-group", label: "Toggle Group" },
]
const FEEDBACK: NavItem[] = [
  { id: "badge", label: "Badge" },
  { id: "skeleton", label: "Skeleton" },
  { id: "spinner", label: "Spinner" },
  { id: "separator", label: "Separator" },
]
const STRUCTURE: NavItem[] = [
  { id: "tabs", label: "Tabs" },
  { id: "collapsible", label: "Collapsible" },
  { id: "dialog", label: "Dialog" },
  { id: "kbd", label: "Kbd" },
]
const OVERLAY: NavItem[] = [
  { id: "popover", label: "Popover" },
  { id: "menu", label: "Menu" },
  { id: "context-menu", label: "Context Menu" },
  { id: "menubar", label: "Menubar" },
  { id: "tooltip", label: "Tooltip" },
  { id: "preview-card", label: "Preview Card" },
]
const SURFACE: NavItem[] = [
  { id: "accordion", label: "Accordion" },
  { id: "alert-dialog", label: "Alert Dialog" },
  { id: "drawer", label: "Drawer" },
  { id: "sidebar", label: "Sidebar" },
  { id: "toast", label: "Toast" },
  { id: "meter", label: "Meter" },
  { id: "scroll-area", label: "Scroll Area" },
  { id: "toolbar", label: "Toolbar" },
  { id: "nav-menu", label: "Navigation Menu" },
]
const NAVIGATION: NavItem[] = [
  { id: "breadcrumb", label: "Breadcrumb" },
  { id: "pagination", label: "Pagination" },
  { id: "rating", label: "Rating" },
  { id: "stepper", label: "Stepper" },
  { id: "timeline", label: "Timeline" },
]
const AUTH: NavItem[] = [
  { id: "signup", label: "Sign up" },
  { id: "magic-link", label: "Magic link" },
  { id: "twofactor", label: "Two-factor" },
]
const PRODUCT: NavItem[] = [
  { id: "pricing", label: "Pricing" },
  { id: "activity", label: "Activity feed" },
  { id: "changelog", label: "Changelog" },
]
export const BACKGROUNDS: NavItem[] = [
  { id: "aurora", label: "Aurora" },
  { id: "waves", label: "Waves" },
  { id: "line-waves", label: "Line waves" },
  { id: "threads", label: "Threads" },
  { id: "silk", label: "Silk" },
  { id: "plasma", label: "Plasma" },
  { id: "iridescence", label: "Iridescence" },
  { id: "dot-grid", label: "Dot grid" },
  { id: "ripple-grid", label: "Ripple grid" },
  { id: "pixel-snow", label: "Pixel snow" },
  { id: "beams", label: "Beams" },
  { id: "light-rays", label: "Light rays" },
  { id: "side-rays", label: "Side rays" },
  { id: "light-pillar", label: "Light pillar" },
  { id: "soft-aurora", label: "Soft aurora" },
  { id: "grid-motion", label: "Grid motion" },
  { id: "grid-scan", label: "Grid scan" },
  { id: "grid-distortion", label: "Grid distortion" },
  { id: "dot-field", label: "Dot field" },
  { id: "color-bends", label: "Color bends" },
  { id: "gradient-blinds", label: "Gradient blinds" },
  { id: "grainient", label: "Grainient" },
  { id: "plasma-wave", label: "Plasma wave" },
  { id: "floating-lines", label: "Floating lines" },
  { id: "radar-sweep", label: "Radar" },
  { id: "dither", label: "Dither" },
  { id: "letter-glitch", label: "Letter glitch" },
  { id: "shape-grid", label: "Shape grid" },
  { id: "lightning", label: "Lightning" },
  { id: "orb", label: "Orb" },
  { id: "prism", label: "Prism" },
  { id: "galaxy", label: "Galaxy" },
  { id: "liquid-chrome", label: "Liquid chrome" },
  { id: "dark-veil", label: "Dark veil" },
  { id: "balatro", label: "Balatro" },
  { id: "liquid-ether", label: "Liquid ether" },
  { id: "ballpit", label: "Ballpit" },
  { id: "particles", label: "Particles" },
  { id: "hyperspeed", label: "Hyperspeed" },
  { id: "lightfall", label: "Lightfall" },
  { id: "pixel-blast", label: "Pixel blast" },
  { id: "prismatic-burst", label: "Prismatic burst" },
  { id: "evil-eye", label: "Evil eye" },
  { id: "faulty-terminal", label: "Faulty terminal" },
  { id: "ferrofluid", label: "Ferrofluid" },
]
export const TEXT: NavItem[] = [
  { id: "gradient-text", label: "Gradient text" },
  { id: "shiny-text", label: "Shiny text" },
  { id: "glitch-text", label: "Glitch text" },
  { id: "split-text", label: "Split text" },
  { id: "rotating-text", label: "Rotating text" },
  { id: "count-up", label: "Count up" },
  { id: "text-type", label: "Text type" },
  { id: "blur-text", label: "Blur text" },
  { id: "decrypted-text", label: "Decrypted text" },
  { id: "scramble-text", label: "Scramble text" },
  { id: "shuffle", label: "Shuffle" },
  { id: "falling-text", label: "Falling text" },
  { id: "scroll-reveal", label: "Scroll reveal" },
  { id: "scroll-float", label: "Scroll float" },
  { id: "scroll-velocity", label: "Scroll velocity" },
  { id: "text-cursor", label: "Text cursor" },
  { id: "text-pressure", label: "Text pressure" },
  { id: "variable-proximity", label: "Variable proximity" },
  { id: "true-focus", label: "True focus" },
  { id: "circular-text", label: "Circular text" },
  { id: "curved-loop", label: "Curved loop" },
  { id: "fuzzy-text", label: "Fuzzy text" },
  { id: "ascii-text", label: "ASCII text" },
]
export const ANIMATIONS: NavItem[] = [
  { id: "animated-content", label: "Animated content" },
  { id: "fade-content", label: "Fade content" },
  { id: "gradual-blur", label: "Gradual blur" },
  { id: "star-border", label: "Star border" },
  { id: "electric-border", label: "Electric border" },
  { id: "glare-hover", label: "Glare hover" },
  { id: "magnet", label: "Magnet" },
  { id: "click-spark", label: "Click spark" },
  { id: "blob-cursor", label: "Blob cursor" },
  { id: "crosshair", label: "Crosshair" },
  { id: "ghost-cursor", label: "Ghost cursor" },
  { id: "splash-cursor", label: "Splash cursor" },
  { id: "target-cursor", label: "Target cursor" },
  { id: "pixel-trail", label: "Pixel trail" },
  { id: "image-trail", label: "Image trail" },
  { id: "meta-balls", label: "Meta balls" },
  { id: "metallic-paint", label: "Metallic paint" },
  { id: "noise", label: "Noise" },
  { id: "cubes", label: "Cubes" },
  { id: "ribbons", label: "Ribbons" },
  { id: "shape-blur", label: "Shape blur" },
  { id: "strands", label: "Strands" },
  { id: "laser-flow", label: "Laser flow" },
  { id: "antigravity", label: "Antigravity" },
  { id: "logo-loop", label: "Logo loop" },
  { id: "magic-rings", label: "Magic rings" },
  { id: "magnet-lines", label: "Magnet lines" },
  { id: "orbit-images", label: "Orbit images" },
  { id: "pixel-transition", label: "Pixel transition" },
  { id: "sticker-peel", label: "Sticker peel" },
]

export const GROUPS: NavGroup[] = [
  { title: "Overview", items: [{ id: "getting-started", label: "Quick start" }] },
  {
    title: "Handbook",
    items: [
      { id: "styling", label: "Styling" },
      { id: "composition", label: "Composition" },
      { id: "seeds", label: "Seeds" },
      { id: "motion", label: "Animation" },
      { id: "accessibility", label: "Accessibility" },
    ],
  },
  {
    title: "Examples",
    items: [
      { id: "dashboard", label: "Dashboard" },
      { id: "shell", label: "App shell" },
      { id: "monitoring", label: "Monitoring" },
      { id: "team", label: "Team" },
      { id: "usage", label: "Usage & billing" },
      { id: "signin", label: "Sign in" },
      ...AUTH,
      ...PRODUCT,
    ],
  },
  {
    title: "Components",
    items: [
      { id: "area", label: "Area Chart" },
      { id: "line", label: "Line Chart" },
      { id: "bar", label: "Bar Chart" },
      { id: "pie", label: "Pie Chart" },
      { id: "sparkline", label: "Sparkline" },
      { id: "button", label: "Button" },
      { id: "avatar", label: "Avatar" },
      { id: "gradient", label: "Gradient" },
      { id: "image", label: "Image" },
      ...FORM,
      ...FIELD,
      ...SELECTION,
      ...FEEDBACK,
      ...STRUCTURE,
      ...OVERLAY,
      ...SURFACE,
      ...NAVIGATION,
    ],
  },
  { title: "Backgrounds", items: BACKGROUNDS },
  { title: "Text", items: TEXT },
  { title: "Animations", items: ANIMATIONS },
  { title: "Utils", items: [{ id: "palette", label: "Palette" }] },
]
