// Public API for Dither Kit (Svelte 5). Mirrors the Vue kit's surface as the
// port lands in batches. Ported so far: the four canonical control/effect
// patterns plus the generative canvas-background family (WebGL-free canvas +
// Bayer, all driven by the shared `ditherBackground` action).

export { default as Aurora, type AuroraParams } from "./backgrounds/Aurora.svelte"

// Generative canvas backgrounds (self-sizing `relative h-full w-full` roots).
export { default as Noise, type NoiseParams } from "./backgrounds/Noise.svelte"
export { default as Dither, type DitherBgParams } from "./backgrounds/Dither.svelte"
export { default as Cubes, type CubesParams } from "./backgrounds/Cubes.svelte"
export { default as PixelSnow, type PixelSnowParams } from "./backgrounds/PixelSnow.svelte"
export { default as Plasma, type PlasmaParams } from "./backgrounds/Plasma.svelte"
export { default as Iridescence, type IridescenceParams } from "./backgrounds/Iridescence.svelte"
export { default as Prism, type PrismParams } from "./backgrounds/Prism.svelte"
export { default as ShapeGrid, type ShapeGridParams } from "./backgrounds/ShapeGrid.svelte"
export { default as MetallicPaint, type MetallicPaintParams } from "./backgrounds/MetallicPaint.svelte"
export { default as Grainient, type GrainientParams } from "./backgrounds/Grainient.svelte"
export { default as ColorBends, type ColorBendsParams } from "./backgrounds/ColorBends.svelte"
export { default as PlasmaWave, type PlasmaWaveParams } from "./backgrounds/PlasmaWave.svelte"
export { default as LiquidChrome, type LiquidChromeParams } from "./backgrounds/LiquidChrome.svelte"
export { default as PrismaticBurst, type PrismaticBurstParams } from "./backgrounds/PrismaticBurst.svelte"
export { default as LetterGlitch, type LetterGlitchParams } from "./backgrounds/LetterGlitch.svelte"
export { default as Orb, type OrbParams } from "./backgrounds/Orb.svelte"
export { default as LaserFlow, type LaserFlowParams } from "./backgrounds/LaserFlow.svelte"
export { default as Balatro, type BalatroParams } from "./backgrounds/Balatro.svelte"
export { default as PixelBlast, type PixelBlastParams } from "./backgrounds/PixelBlast.svelte"
export { default as GradientBlinds, type GradientBlindsParams } from "./backgrounds/GradientBlinds.svelte"
export { default as DarkVeil, type DarkVeilParams } from "./backgrounds/DarkVeil.svelte"
export { default as Hyperspeed, type HyperspeedParams } from "./backgrounds/Hyperspeed.svelte"
export { default as LightPillar, type LightPillarParams } from "./backgrounds/LightPillar.svelte"
export { default as SoftAurora, type SoftAuroraParams } from "./backgrounds/SoftAurora.svelte"
export { default as Lightning, type LightningParams } from "./backgrounds/Lightning.svelte"
export { default as Galaxy, type GalaxyParams } from "./backgrounds/Galaxy.svelte"
export { default as Lightfall, type LightfallParams } from "./backgrounds/Lightfall.svelte"
export { default as GridMotion, type GridMotionParams } from "./backgrounds/GridMotion.svelte"
export { default as FloatingLines, type FloatingLinesParams } from "./backgrounds/FloatingLines.svelte"
export { default as GridScan, type GridScanParams } from "./backgrounds/GridScan.svelte"
export { default as Beams, type BeamsParams } from "./backgrounds/Beams.svelte"
export { default as Strands, type StrandsParams } from "./backgrounds/Strands.svelte"
export { default as Silk, type SilkParams } from "./backgrounds/Silk.svelte"
export { default as RippleGrid, type RippleGridParams } from "./backgrounds/RippleGrid.svelte"
export { default as LightRays, type RaysParams } from "./backgrounds/LightRays.svelte"
export { default as LineWaves, type LineWavesParams } from "./backgrounds/LineWaves.svelte"
export { default as Threads, type ThreadsParams } from "./backgrounds/Threads.svelte"
export { default as SideRays } from "./backgrounds/SideRays.svelte"
export { default as Radar, type RadarParams } from "./backgrounds/Radar.svelte"
// Pointer-reactive backgrounds (track the cursor via <svelte:window>).
export { default as GridDistortion, type GridDistortionParams } from "./backgrounds/GridDistortion.svelte"
export { default as EvilEye, type EvilEyeParams } from "./backgrounds/EvilEye.svelte"
export { default as MetaBalls, type MetaBallsParams } from "./backgrounds/MetaBalls.svelte"
export { default as DotGrid, type DotGridParams } from "./backgrounds/DotGrid.svelte"
export { default as Particles, type ParticlesParams } from "./backgrounds/Particles.svelte"
export { default as LiquidEther, type LiquidEtherParams } from "./backgrounds/LiquidEther.svelte"
export { default as DotField, type DotFieldParams } from "./backgrounds/DotField.svelte"
export { default as Ballpit, type BallpitParams } from "./backgrounds/Ballpit.svelte"
export { default as ShapeBlur, type ShapeBlurParams } from "./backgrounds/ShapeBlur.svelte"
export { default as Waves, type WavesParams } from "./backgrounds/Waves.svelte"
export { default as Ribbons, type RibbonsParams } from "./backgrounds/Ribbons.svelte"
export { default as Ferrofluid, type FerrofluidParams, type FlowDirection } from "./backgrounds/Ferrofluid.svelte"
export { default as FaultyTerminal, type FaultyTerminalParams } from "./backgrounds/FaultyTerminal.svelte"
// Text & motion effects (DOM/CSS, reduced-motion aware; reveal via `inView`).
export { default as ShinyText } from "./text/ShinyText.svelte"
export { default as GradientText } from "./text/GradientText.svelte"
export { default as GlitchText } from "./text/GlitchText.svelte"
export { default as BlurText } from "./text/BlurText.svelte"
export { default as RotatingText } from "./text/RotatingText.svelte"
export { default as CountUp } from "./text/CountUp.svelte"
export { default as NumberFlow } from "./text/NumberFlow.svelte"
export { default as GradualBlur } from "./text/GradualBlur.svelte"
export { default as StarBorder } from "./text/StarBorder.svelte"
export { default as GlareHover } from "./text/GlareHover.svelte"
export { default as FadeContent } from "./text/FadeContent.svelte"
export { default as AnimatedContent } from "./text/AnimatedContent.svelte"
export { default as SplitText } from "./text/SplitText.svelte"
export { default as ScrollFloat } from "./text/ScrollFloat.svelte"
export { default as DecryptedText } from "./text/DecryptedText.svelte"
export { default as CircularText } from "./text/CircularText.svelte"
export { default as ElectricBorder } from "./text/ElectricBorder.svelte"
export { default as ScrollReveal } from "./text/ScrollReveal.svelte"
export { default as TrueFocus } from "./text/TrueFocus.svelte"
export { default as Magnet } from "./text/Magnet.svelte"
export { default as TextType } from "./text/TextType.svelte"
export { default as ScrambleText } from "./text/ScrambleText.svelte"
export { inView } from "./runtime/in-view"
export {
  default as DitherButton,
  type ButtonVariant,
  type DitherRenderMode,
  type PrecompiledDither,
} from "./controls/DitherButton.svelte"
export { default as DitherField } from "./controls/DitherField.svelte"
export { default as DitherInput } from "./controls/DitherInput.svelte"

// ===== Full port (parallel batches: charts, effects, controls, widgets) =====
// Chart roots (composable) + parts + reactive context
export { default as Area } from "./charts/Area.svelte"
export { default as Line } from "./charts/Line.svelte"
export { default as Bar } from "./charts/Bar.svelte"
export { default as Pie } from "./charts/Pie.svelte"
export { default as CartesianSeries } from "./charts/CartesianSeries.svelte"
export { default as Dot } from "./charts/Dot.svelte"
export { default as ActiveDot } from "./charts/ActiveDot.svelte"
export { default as Grid } from "./charts/Grid.svelte"
export { default as XAxis } from "./charts/XAxis.svelte"
export { default as YAxis } from "./charts/YAxis.svelte"
export { default as RadarFrame } from "./charts/RadarFrame.svelte"
export { default as Legend } from "./charts/Legend.svelte"
export { default as Tooltip, type TooltipVariant } from "./charts/Tooltip.svelte"
export { default as AreaChart } from "./charts/AreaChart.svelte"
export { default as LineChart } from "./charts/LineChart.svelte"
export { default as BarChart } from "./charts/BarChart.svelte"
export { default as PieChart } from "./charts/PieChart.svelte"
export { default as RadarChart } from "./charts/RadarChart.svelte"
export { default as Sparkline } from "./charts/Sparkline.svelte"

// Text & cursor effects
export { default as AsciiText } from "./text/AsciiText.svelte"
export { default as ScrollVelocity } from "./text/ScrollVelocity.svelte"
export { default as VariableProximity } from "./text/VariableProximity.svelte"
export { default as TextPressure } from "./text/TextPressure.svelte"
export { default as FallingText } from "./text/FallingText.svelte"
export { default as Shuffle } from "./text/Shuffle.svelte"
export { default as FuzzyText } from "./text/FuzzyText.svelte"
export { default as CurvedLoop } from "./text/CurvedLoop.svelte"
export { default as LogoLoop } from "./text/LogoLoop.svelte"
export { default as MagicRings } from "./text/MagicRings.svelte"
export { default as OrbitImages } from "./text/OrbitImages.svelte"
export { default as StickerPeel } from "./text/StickerPeel.svelte"
export { default as PixelTransition } from "./text/PixelTransition.svelte"
export { default as PixelTrail } from "./text/PixelTrail.svelte"
export { default as ImageTrail } from "./text/ImageTrail.svelte"
export { default as ClickSpark } from "./text/ClickSpark.svelte"
export { default as SplashCursor } from "./text/SplashCursor.svelte"
export { default as GhostCursor } from "./text/GhostCursor.svelte"
export { default as BlobCursor } from "./text/BlobCursor.svelte"
export { default as TextCursor } from "./text/TextCursor.svelte"
export { default as TargetCursor } from "./text/TargetCursor.svelte"
export { default as Crosshair } from "./text/Crosshair.svelte"
export { default as MagnetLines } from "./text/MagnetLines.svelte"
export { default as Antigravity } from "./text/Antigravity.svelte"

// Form controls
export { default as DitherSelect, type Option } from "./controls/DitherSelect.svelte"
export { default as DitherWheelPicker, type WheelOption } from "./controls/WheelPicker.svelte"
export { default as DitherCombobox } from "./controls/DitherCombobox.svelte"
export { default as DitherCheckbox } from "./controls/DitherCheckbox.svelte"
export { default as DitherCheckboxGroup } from "./controls/DitherCheckboxGroup.svelte"
export { default as DitherRadioGroup } from "./controls/DitherRadioGroup.svelte"
export { default as DitherToggle } from "./controls/DitherToggle.svelte"
export { default as DitherToggleGroup } from "./controls/DitherToggleGroup.svelte"
export { default as DitherAutocomplete } from "./controls/DitherAutocomplete.svelte"
export { default as DitherNumberField } from "./controls/DitherNumberField.svelte"
export { default as DitherOtpField } from "./controls/DitherOtpField.svelte"
export { default as DitherTextarea } from "./controls/DitherTextarea.svelte"
export { default as DitherForm } from "./controls/DitherForm.svelte"
export { default as DitherFieldset } from "./controls/DitherFieldset.svelte"
export { default as DitherKbd } from "./controls/DitherKbd.svelte"
export { default as DitherRating } from "./controls/DitherRating.svelte"
export { default as DitherSlider, type SliderVariant } from "./controls/DitherSlider.svelte"
export { default as DitherSwitch } from "./controls/DitherSwitch.svelte"
export { default as DitherProgress } from "./controls/DitherProgress.svelte"
export { default as DitherMeter } from "./controls/DitherMeter.svelte"
export { default as DitherBadge, type BadgeVariant } from "./controls/DitherBadge.svelte"
export { default as DitherSkeleton } from "./controls/DitherSkeleton.svelte"
export { default as DitherSeparator, type SeparatorOrientation } from "./controls/DitherSeparator.svelte"
export { default as DitherStepper, type Step } from "./controls/DitherStepper.svelte"

// Overlays, nav & sidebar
export { default as DitherGradient, type GradientDirection } from "./overlays/DitherGradient.svelte"
export { default as DitherSidebar, type SidebarVariant, type SidebarCollapse, type SidebarDensity, type SidebarContext } from "./overlays/DitherSidebar.svelte"
export { default as DitherSidebarGroup } from "./overlays/DitherSidebarGroup.svelte"
export { default as DitherSidebarItem } from "./overlays/DitherSidebarItem.svelte"
export { default as DitherSidebarSub } from "./overlays/DitherSidebarSub.svelte"
export { default as DitherTabs, type TabsVariant, type TabItem, type TabsContext } from "./overlays/DitherTabs.svelte"
export { default as DitherTabPanel } from "./overlays/DitherTabPanel.svelte"
export { default as DitherDrawer, type DrawerSide, type DrawerChannel } from "./overlays/DitherDrawer.svelte"
export { default as DitherDrawerIndent } from "./overlays/DitherDrawerIndent.svelte"
export { default as DitherDialog } from "./overlays/DitherDialog.svelte"
export { default as DitherCenterMorphModal } from "./overlays/CenterMorphModal.svelte"
export { default as DitherCommand, type CommandItem } from "./overlays/DitherCommand.svelte"
export { default as DitherAlertDialog } from "./overlays/DitherAlertDialog.svelte"
export { default as DitherMenu, type MenuItem } from "./overlays/DitherMenu.svelte"
export { default as DitherContextMenu, type ContextMenuItem } from "./overlays/DitherContextMenu.svelte"
export { default as DitherMenubar, type MenubarItem, type MenubarMenu } from "./overlays/DitherMenubar.svelte"
export { default as DitherNavMenu, type NavMenuItem } from "./overlays/DitherNavMenu.svelte"
export { default as DitherPopover } from "./overlays/DitherPopover.svelte"
export { default as DitherTooltip } from "./overlays/DitherTooltip.svelte"
export { default as DitherPreviewCard } from "./overlays/DitherPreviewCard.svelte"
export { default as DitherToaster } from "./overlays/DitherToaster.svelte"

// Widgets & layout
export { default as DitherImage } from "./widgets/DitherImage.svelte"
export { default as DitherAvatar, type AvatarMirror } from "./widgets/DitherAvatar.svelte"
export { default as DitherSpinner } from "./widgets/DitherSpinner.svelte"
export { default as DitherAccordion, type AccordionItem } from "./widgets/DitherAccordion.svelte"
export { default as DitherBouncyAccordion, type BouncyItem } from "./widgets/BouncyAccordion.svelte"
export { default as DitherCollapsible } from "./widgets/DitherCollapsible.svelte"
export { default as DitherBreadcrumb, type Crumb } from "./widgets/DitherBreadcrumb.svelte"
export { default as DitherPagination } from "./widgets/DitherPagination.svelte"
export { default as DitherToolbar } from "./widgets/DitherToolbar.svelte"
export { default as DitherScrollArea } from "./widgets/DitherScrollArea.svelte"
export { default as DitherShell } from "./widgets/DitherShell.svelte"
export { default as DitherRail } from "./widgets/DitherRail.svelte"
export { default as DitherConsole, type ConsoleLevel, type ConsoleLine } from "./widgets/DitherConsole.svelte"
export { default as DitherCanvas } from "./widgets/DitherCanvas.svelte"
export { default as DitherGrid } from "./widgets/DitherGrid.svelte"
export { default as DitherSwipeArea } from "./widgets/DitherSwipeArea.svelte"
export { default as DitherTimeline, type TimelineItem } from "./widgets/DitherTimeline.svelte"
export { default as DitherExpandTabs, type ExpandTab } from "./widgets/ExpandTabs.svelte"
export { default as DitherIsland } from "./widgets/Island.svelte"
export { default as DitherCardStack } from "./widgets/CardStack.svelte"
export { default as DitherScrollProgress } from "./widgets/ScrollProgress.svelte"
export { default as DitherDock, type DockItem } from "./widgets/Dock.svelte"
export { default as DitherPreviewRail, type PreviewRailItem } from "./widgets/PreviewRail.svelte"
export { default as DitherVideoPlayer } from "./widgets/DitherVideoPlayer.svelte"
export { default as DitherBracket, type BracketMatch } from "./widgets/DitherBracket.svelte"
export { default as DitherSchedule, type ScheduleEvent } from "./widgets/DitherSchedule.svelte"
export { default as DitherInfiniteCanvas } from "./widgets/DitherInfiniteCanvas.svelte"
export { default as DitherSnapButton } from "./widgets/SnapButton.svelte"
export { default as DitherExpandingArrow } from "./widgets/ExpandingArrow.svelte"
export { default as DitherSlideAction } from "./widgets/SlideAction.svelte"
export { default as DitherHoldAction } from "./widgets/HoldAction.svelte"
export { default as DitherWalletCard, type WalletAccount, type WalletAction } from "./widgets/WalletCard.svelte"
export { default as DitherNotificationStack, type NotificationItem, type NotificationStackVariant } from "./widgets/NotificationStack.svelte"
export { default as DitherGooeyMenu, type GooeyItem } from "./widgets/GooeyMenu.svelte"

// Shared runtime + tokens (also portable on their own).
export { ditherBackground, type DitherBackgroundParams } from "./runtime/use-dither-background"
export { CONTROL, CONTROL_BUTTON, POPOVER, setField, useField, type FieldContext } from "./runtime/control"

// Engine primitives are framework-agnostic and copied verbatim from the Vue
// kit; import them from their deep paths (e.g. "dither-kit-svelte/engine/palette")
// avoid barrel name collisions. Only the className helper is surfaced here.
export { cn } from "./runtime/lib"
export { cssColor, rgb, type DitherColor } from "./engine/palette"
