// Public API for Dither Kit (Svelte 5). Mirrors the Vue kit's surface as the
// port lands in batches. Ported so far: the four canonical control/effect
// patterns plus the generative canvas-background family (WebGL-free canvas +
// Bayer, all driven by the shared `ditherBackground` action).

export { default as Aurora, type AuroraParams } from "./Aurora.svelte"

// Generative canvas backgrounds (self-sizing `relative h-full w-full` roots).
export { default as Noise, type NoiseParams } from "./Noise.svelte"
export { default as Dither, type DitherBgParams } from "./Dither.svelte"
export { default as Cubes, type CubesParams } from "./Cubes.svelte"
export { default as PixelSnow, type PixelSnowParams } from "./PixelSnow.svelte"
export { default as Plasma, type PlasmaParams } from "./Plasma.svelte"
export { default as Iridescence, type IridescenceParams } from "./Iridescence.svelte"
export { default as Prism, type PrismParams } from "./Prism.svelte"
export { default as ShapeGrid, type ShapeGridParams } from "./ShapeGrid.svelte"
export { default as MetallicPaint, type MetallicPaintParams } from "./MetallicPaint.svelte"
export { default as Grainient, type GrainientParams } from "./Grainient.svelte"
export { default as ColorBends, type ColorBendsParams } from "./ColorBends.svelte"
export { default as PlasmaWave, type PlasmaWaveParams } from "./PlasmaWave.svelte"
export { default as LiquidChrome, type LiquidChromeParams } from "./LiquidChrome.svelte"
export { default as PrismaticBurst, type PrismaticBurstParams } from "./PrismaticBurst.svelte"
export { default as LetterGlitch, type LetterGlitchParams } from "./LetterGlitch.svelte"
export { default as Orb, type OrbParams } from "./Orb.svelte"
export { default as LaserFlow, type LaserFlowParams } from "./LaserFlow.svelte"
export { default as Balatro, type BalatroParams } from "./Balatro.svelte"
export { default as PixelBlast, type PixelBlastParams } from "./PixelBlast.svelte"
export { default as GradientBlinds, type GradientBlindsParams } from "./GradientBlinds.svelte"
export { default as DarkVeil, type DarkVeilParams } from "./DarkVeil.svelte"
export { default as Hyperspeed, type HyperspeedParams } from "./Hyperspeed.svelte"
export { default as LightPillar, type LightPillarParams } from "./LightPillar.svelte"
export { default as SoftAurora, type SoftAuroraParams } from "./SoftAurora.svelte"
export { default as Lightning, type LightningParams } from "./Lightning.svelte"
export { default as Galaxy, type GalaxyParams } from "./Galaxy.svelte"
export { default as Lightfall, type LightfallParams } from "./Lightfall.svelte"
export { default as GridMotion, type GridMotionParams } from "./GridMotion.svelte"
export { default as FloatingLines, type FloatingLinesParams } from "./FloatingLines.svelte"
export { default as GridScan, type GridScanParams } from "./GridScan.svelte"
export { default as Beams, type BeamsParams } from "./Beams.svelte"
export { default as Strands, type StrandsParams } from "./Strands.svelte"
export { default as Silk, type SilkParams } from "./Silk.svelte"
export { default as RippleGrid, type RippleGridParams } from "./RippleGrid.svelte"
export { default as LightRays, type RaysParams } from "./LightRays.svelte"
export { default as LineWaves, type LineWavesParams } from "./LineWaves.svelte"
export { default as Threads, type ThreadsParams } from "./Threads.svelte"
export { default as SideRays } from "./SideRays.svelte"
export { default as Radar, type RadarParams } from "./Radar.svelte"
// Pointer-reactive backgrounds (track the cursor via <svelte:window>).
export { default as GridDistortion, type GridDistortionParams } from "./GridDistortion.svelte"
export { default as EvilEye, type EvilEyeParams } from "./EvilEye.svelte"
export { default as MetaBalls, type MetaBallsParams } from "./MetaBalls.svelte"
export { default as DotGrid, type DotGridParams } from "./DotGrid.svelte"
export { default as Particles, type ParticlesParams } from "./Particles.svelte"
export { default as LiquidEther, type LiquidEtherParams } from "./LiquidEther.svelte"
export { default as DotField, type DotFieldParams } from "./DotField.svelte"
export { default as Ballpit, type BallpitParams } from "./Ballpit.svelte"
export { default as ShapeBlur, type ShapeBlurParams } from "./ShapeBlur.svelte"
export { default as Waves, type WavesParams } from "./Waves.svelte"
export { default as Ribbons, type RibbonsParams } from "./Ribbons.svelte"
export { default as Ferrofluid, type FerrofluidParams, type FlowDirection } from "./Ferrofluid.svelte"
export { default as FaultyTerminal, type FaultyTerminalParams } from "./FaultyTerminal.svelte"
// Text & motion effects (DOM/CSS, reduced-motion aware; reveal via `inView`).
export { default as ShinyText } from "./ShinyText.svelte"
export { default as GradientText } from "./GradientText.svelte"
export { default as GlitchText } from "./GlitchText.svelte"
export { default as BlurText } from "./BlurText.svelte"
export { default as RotatingText } from "./RotatingText.svelte"
export { default as CountUp } from "./CountUp.svelte"
export { default as GradualBlur } from "./GradualBlur.svelte"
export { default as StarBorder } from "./StarBorder.svelte"
export { default as GlareHover } from "./GlareHover.svelte"
export { default as FadeContent } from "./FadeContent.svelte"
export { default as AnimatedContent } from "./AnimatedContent.svelte"
export { default as SplitText } from "./SplitText.svelte"
export { default as ScrollFloat } from "./ScrollFloat.svelte"
export { default as DecryptedText } from "./DecryptedText.svelte"
export { default as CircularText } from "./CircularText.svelte"
export { default as ElectricBorder } from "./ElectricBorder.svelte"
export { default as ScrollReveal } from "./ScrollReveal.svelte"
export { default as TrueFocus } from "./TrueFocus.svelte"
export { default as Magnet } from "./Magnet.svelte"
export { default as TextType } from "./TextType.svelte"
export { default as ScrambleText } from "./ScrambleText.svelte"
export { inView } from "./in-view"
export {
  default as DitherButton,
  type ButtonVariant,
  type DitherRenderMode,
  type PrecompiledDither,
} from "./DitherButton.svelte"
export { default as DitherField } from "./DitherField.svelte"
export { default as DitherInput } from "./DitherInput.svelte"

// ===== Full port (parallel batches: charts, effects, controls, widgets) =====
// Charts (parts + reactive context; roots pending)
export { default as Area } from "./Area.svelte"
export { default as Line } from "./Line.svelte"
export { default as Bar } from "./Bar.svelte"
export { default as Pie } from "./Pie.svelte"
export { default as CartesianSeries } from "./CartesianSeries.svelte"
export { default as Dot } from "./Dot.svelte"
export { default as ActiveDot } from "./ActiveDot.svelte"
export { default as Grid } from "./Grid.svelte"
export { default as XAxis } from "./XAxis.svelte"
export { default as YAxis } from "./YAxis.svelte"
export { default as RadarFrame } from "./RadarFrame.svelte"
export { default as Legend } from "./Legend.svelte"
export { default as Tooltip, type TooltipVariant } from "./Tooltip.svelte"

// Text & cursor effects
export { default as AsciiText } from "./AsciiText.svelte"
export { default as ScrollVelocity } from "./ScrollVelocity.svelte"
export { default as VariableProximity } from "./VariableProximity.svelte"
export { default as TextPressure } from "./TextPressure.svelte"
export { default as FallingText } from "./FallingText.svelte"
export { default as Shuffle } from "./Shuffle.svelte"
export { default as FuzzyText } from "./FuzzyText.svelte"
export { default as CurvedLoop } from "./CurvedLoop.svelte"
export { default as LogoLoop } from "./LogoLoop.svelte"
export { default as MagicRings } from "./MagicRings.svelte"
export { default as OrbitImages } from "./OrbitImages.svelte"
export { default as StickerPeel } from "./StickerPeel.svelte"
export { default as PixelTransition } from "./PixelTransition.svelte"
export { default as PixelTrail } from "./PixelTrail.svelte"
export { default as ImageTrail } from "./ImageTrail.svelte"
export { default as ClickSpark } from "./ClickSpark.svelte"
export { default as SplashCursor } from "./SplashCursor.svelte"
export { default as GhostCursor } from "./GhostCursor.svelte"
export { default as BlobCursor } from "./BlobCursor.svelte"
export { default as TextCursor } from "./TextCursor.svelte"
export { default as TargetCursor } from "./TargetCursor.svelte"
export { default as Crosshair } from "./Crosshair.svelte"
export { default as MagnetLines } from "./MagnetLines.svelte"
export { default as Antigravity } from "./Antigravity.svelte"

// Form controls
export { default as DitherSelect, type Option } from "./DitherSelect.svelte"
export { default as DitherCombobox } from "./DitherCombobox.svelte"
export { default as DitherCheckbox } from "./DitherCheckbox.svelte"
export { default as DitherCheckboxGroup } from "./DitherCheckboxGroup.svelte"
export { default as DitherRadioGroup } from "./DitherRadioGroup.svelte"
export { default as DitherToggle } from "./DitherToggle.svelte"
export { default as DitherToggleGroup } from "./DitherToggleGroup.svelte"
export { default as DitherAutocomplete } from "./DitherAutocomplete.svelte"
export { default as DitherNumberField } from "./DitherNumberField.svelte"
export { default as DitherOtpField } from "./DitherOtpField.svelte"
export { default as DitherTextarea } from "./DitherTextarea.svelte"
export { default as DitherForm } from "./DitherForm.svelte"
export { default as DitherFieldset } from "./DitherFieldset.svelte"
export { default as DitherKbd } from "./DitherKbd.svelte"
export { default as DitherRating } from "./DitherRating.svelte"
export { default as DitherSlider, type SliderVariant } from "./DitherSlider.svelte"
export { default as DitherSwitch } from "./DitherSwitch.svelte"
export { default as DitherProgress } from "./DitherProgress.svelte"
export { default as DitherMeter } from "./DitherMeter.svelte"
export { default as DitherBadge, type BadgeVariant } from "./DitherBadge.svelte"
export { default as DitherSkeleton } from "./DitherSkeleton.svelte"
export { default as DitherSeparator, type SeparatorOrientation } from "./DitherSeparator.svelte"
export { default as DitherStepper, type Step } from "./DitherStepper.svelte"

// Overlays, nav & sidebar
export { default as DitherGradient, type GradientDirection } from "./DitherGradient.svelte"
export { default as DitherSidebar, type SidebarVariant, type SidebarCollapse, type SidebarDensity, type SidebarContext } from "./DitherSidebar.svelte"
export { default as DitherSidebarGroup } from "./DitherSidebarGroup.svelte"
export { default as DitherSidebarItem } from "./DitherSidebarItem.svelte"
export { default as DitherSidebarSub } from "./DitherSidebarSub.svelte"
export { default as DitherTabs, type TabsVariant, type TabItem, type TabsContext } from "./DitherTabs.svelte"
export { default as DitherTabPanel } from "./DitherTabPanel.svelte"
export { default as DitherDrawer, type DrawerSide, type DrawerChannel } from "./DitherDrawer.svelte"
export { default as DitherDrawerIndent } from "./DitherDrawerIndent.svelte"
export { default as DitherDialog } from "./DitherDialog.svelte"
export { default as DitherAlertDialog } from "./DitherAlertDialog.svelte"
export { default as DitherMenu, type MenuItem } from "./DitherMenu.svelte"
export { default as DitherContextMenu, type ContextMenuItem } from "./DitherContextMenu.svelte"
export { default as DitherMenubar, type MenubarItem, type MenubarMenu } from "./DitherMenubar.svelte"
export { default as DitherNavMenu, type NavMenuItem } from "./DitherNavMenu.svelte"
export { default as DitherPopover } from "./DitherPopover.svelte"
export { default as DitherTooltip } from "./DitherTooltip.svelte"
export { default as DitherPreviewCard } from "./DitherPreviewCard.svelte"
export { default as DitherToaster } from "./DitherToaster.svelte"

// Widgets & layout
export { default as DitherImage } from "./DitherImage.svelte"
export { default as DitherAvatar, type AvatarMirror } from "./DitherAvatar.svelte"
export { default as DitherSpinner } from "./DitherSpinner.svelte"
export { default as DitherAccordion, type AccordionItem } from "./DitherAccordion.svelte"
export { default as DitherCollapsible } from "./DitherCollapsible.svelte"
export { default as DitherBreadcrumb, type Crumb } from "./DitherBreadcrumb.svelte"
export { default as DitherPagination } from "./DitherPagination.svelte"
export { default as DitherToolbar } from "./DitherToolbar.svelte"
export { default as DitherScrollArea } from "./DitherScrollArea.svelte"
export { default as DitherSwipeArea } from "./DitherSwipeArea.svelte"
export { default as DitherTimeline, type TimelineItem } from "./DitherTimeline.svelte"

// Shared runtime + tokens (also portable on their own).
export { ditherBackground, type DitherBackgroundParams } from "./use-dither-background"
export { CONTROL, CONTROL_BUTTON, POPOVER, setField, useField, type FieldContext } from "./control"

// Engine primitives are framework-agnostic and copied verbatim from the Vue
// kit; import them from their deep paths (e.g. "dither-kit-svelte/palette") to
// avoid barrel name collisions. Only the className helper is surfaced here.
export { cn } from "./lib"
