import type { PixelColor } from "@dither-kit"

export type PropSpec =
  | { key: string; kind: "text"; def: string }
  | { key: string; kind: "boolean"; def: boolean }
  | { key: string; kind: "number"; def: number; min?: number; max?: number; step?: number }
  | { key: string; kind: "select"; def: string; options: readonly string[] }
  | { key: string; kind: "color"; def: PixelColor }
  | { key: string; kind: "list"; def: string[] }

export type ComponentGroup = "inputs" | "navigation" | "display" | "overlays" | "structure"
export type ComponentDemo =
  | "alert"
  | "dialog"
  | "drawer"
  | "drawer-indent"
  | "field"
  | "fieldset"
  | "form"
  | "popover"
  | "preview-card"
  | "sidebar"
  | "swipe-area"
  | "tab-panel"
  | "toaster"
  | "toolbar"

export type ComponentEntry = {
  is: string
  label: string
  group: ComponentGroup
  frame: { w: number; h: number }
  props: PropSpec[]
  slotText?: string
  vmodel?: { def: unknown; prop?: string; event?: string }
  mapProps?: (p: Record<string, unknown>) => Record<string, unknown>
  demo?: ComponentDemo
}

const color = (def: PixelColor = "blue"): PropSpec => ({ key: "color", kind: "color", def })
const bool = (key: string, def = false): PropSpec => ({ key, kind: "boolean", def })
const text = (key: string, def: string): PropSpec => ({ key, kind: "text", def })
const number = (key: string, def: number, min?: number, max?: number, step?: number): PropSpec => ({ key, kind: "number", def, min, max, step })
const select = (key: string, def: string, options: readonly string[]): PropSpec => ({ key, kind: "select", def, options })
const list = (key: string, def: string[]): PropSpec => ({ key, kind: "list", def })
const strList = (v: unknown): string[] =>
  Array.isArray(v) ? v.map(String) : String(v ?? "").split(",").map((s) => s.trim()).filter(Boolean)
const options = (v: unknown) => strList(v).map((label) => ({ value: label.toLowerCase().replace(/\s+/g, "-"), label }))
const optionProps = (p: Record<string, unknown>) => ({ ...p, options: options(p.options) })
const items = (labels: unknown) => strList(labels).map((label) => ({ label }))

export const COMPONENT_REGISTRY: ComponentEntry[] = [
  { is: "DitherSwitch", label: "Switch", group: "inputs", frame: { w: 160, h: 80 }, props: [color(), bool("disabled")], vmodel: { def: true } },
  { is: "DitherCheckbox", label: "Checkbox", group: "inputs", frame: { w: 180, h: 80 }, props: [color(), bool("disabled")], slotText: "Remember me", vmodel: { def: true } },
  { is: "DitherToggle", label: "Toggle", group: "inputs", frame: { w: 160, h: 80 }, props: [color(), bool("disabled")], slotText: "Bold", vmodel: { def: true } },
  { is: "DitherSlider", label: "Slider", group: "inputs", frame: { w: 280, h: 90 }, props: [color(), number("min", 0), number("max", 100), number("step", 1, 0.1, undefined, 0.1), bool("disabled")], vmodel: { def: 40 } },
  { is: "DitherInput", label: "Input", group: "inputs", frame: { w: 280, h: 90 }, props: [text("placeholder", "Type here…"), bool("invalid"), bool("disabled")], vmodel: { def: "" } },
  { is: "DitherTextarea", label: "Textarea", group: "inputs", frame: { w: 300, h: 150 }, props: [text("placeholder", "Write a note…"), number("rows", 4, 2, 12), select("resize", "vertical", ["none", "vertical", "horizontal", "both"]), bool("invalid"), bool("disabled")], vmodel: { def: "" } },
  { is: "DitherNumberField", label: "Number field", group: "inputs", frame: { w: 220, h: 90 }, props: [number("min", 0), number("max", 100), number("step", 1, 0.1, undefined, 0.1), bool("disabled")], vmodel: { def: 24 } },
  { is: "DitherOtpField", label: "OTP field", group: "inputs", frame: { w: 320, h: 90 }, props: [number("length", 6, 3, 8)], vmodel: { def: "" } },
  { is: "DitherSelect", label: "Select", group: "inputs", frame: { w: 280, h: 220 }, props: [color(), list("options", ["One", "Two", "Three"]), text("placeholder", "Select…"), bool("invalid"), bool("disabled")], vmodel: { def: "" }, mapProps: optionProps },
  { is: "DitherCombobox", label: "Combobox", group: "inputs", frame: { w: 280, h: 220 }, props: [color(), list("options", ["Kyoto", "Seoul", "Taipei"]), text("placeholder", "Search…"), bool("disabled")], vmodel: { def: "" }, mapProps: optionProps },
  { is: "DitherAutocomplete", label: "Autocomplete", group: "inputs", frame: { w: 280, h: 220 }, props: [list("suggestions", ["Area chart", "Avatar", "Button"]), text("placeholder", "Search…"), bool("disabled")], vmodel: { def: "" } },
  { is: "DitherRadioGroup", label: "Radio group", group: "inputs", frame: { w: 260, h: 160 }, props: [color(), text("label", "Choose one"), list("options", ["One", "Two", "Three"])], vmodel: { def: "one" }, mapProps: optionProps },
  { is: "DitherCheckboxGroup", label: "Checkbox group", group: "inputs", frame: { w: 260, h: 170 }, props: [color(), text("label", "Choose any"), list("options", ["One", "Two", "Three"])], vmodel: { def: ["one"] }, mapProps: optionProps },
  { is: "DitherToggleGroup", label: "Toggle group", group: "inputs", frame: { w: 300, h: 100 }, props: [color(), select("type", "single", ["single", "multiple"]), list("options", ["Bold", "Italic", "Underline"])], vmodel: { def: "bold" }, mapProps: optionProps },
  { is: "DitherTabs", label: "Tabs", group: "inputs", frame: { w: 340, h: 110 }, props: [color(), list("tabs", ["One", "Two", "Three"]), select("variant", "underline", ["underline", "segmented", "washed"]), select("orientation", "horizontal", ["horizontal", "vertical"])], vmodel: { def: "One" }, mapProps: (p) => ({ ...p, tabs: strList(p.tabs) }) },
  { is: "DitherTabPanel", label: "Tab panel", group: "structure", frame: { w: 340, h: 160 }, props: [text("value", "One")], slotText: "Panel content", demo: "tab-panel" },
  { is: "DitherAccordion", label: "Accordion", group: "inputs", frame: { w: 340, h: 240 }, props: [color(), list("items", ["First", "Second", "Third"]), select("type", "single", ["single", "multiple"])], vmodel: { def: "first" }, mapProps: (p) => ({ ...p, items: strList(p.items).map((title) => ({ value: title.toLowerCase().replace(/\s+/g, "-"), title, content: `${title} content` })) }) },
  { is: "DitherCollapsible", label: "Collapsible", group: "structure", frame: { w: 300, h: 150 }, props: [color(), text("title", "Details")], slotText: "Hidden content", vmodel: { def: true } },

  { is: "DitherBreadcrumb", label: "Breadcrumb", group: "navigation", frame: { w: 320, h: 70 }, props: [list("items", ["Home", "Components", "Button"]), text("separator", "/")], mapProps: (p) => ({ ...p, items: items(p.items) }) },
  { is: "DitherPagination", label: "Pagination", group: "navigation", frame: { w: 380, h: 80 }, props: [number("total", 12, 1, 100), number("siblings", 1, 0, 3)], vmodel: { def: 4, prop: "page", event: "update:page" } },
  { is: "DitherRating", label: "Rating", group: "inputs", frame: { w: 240, h: 90 }, props: [color("orange"), number("max", 5, 1, 10), number("size", 22, 12, 48), bool("readonly"), text("label", "Rating")], vmodel: { def: 3 } },
  { is: "DitherStepper", label: "Stepper", group: "navigation", frame: { w: 480, h: 130 }, props: [list("steps", ["Account", "Profile", "Done"]), number("current", 1, 0, 8)], mapProps: (p) => ({ ...p, steps: items(p.steps) }) },
  { is: "DitherTimeline", label: "Timeline", group: "display", frame: { w: 340, h: 250 }, props: [list("items", ["Created", "Reviewed", "Published"]), number("dotSize", 12, 6, 24)], mapProps: (p) => ({ ...p, items: strList(p.items).map((title, i) => ({ title, time: `${i + 9}:00`, body: `${title} event` })) }) },
  { is: "DitherNavMenu", label: "Navigation menu", group: "navigation", frame: { w: 360, h: 90 }, props: [color(), list("items", ["Overview", "Components", "Examples"])], vmodel: { def: "Overview" }, mapProps: (p) => ({ ...p, items: items(p.items) }) },

  { is: "DitherBadge", label: "Badge", group: "display", frame: { w: 160, h: 80 }, props: [color(), select("variant", "gradient", ["gradient", "solid", "dotted", "hatched"])], slotText: "beta" },
  { is: "DitherKbd", label: "Kbd", group: "display", frame: { w: 140, h: 80 }, props: [], slotText: "⌘K" },
  { is: "DitherProgress", label: "Progress", group: "display", frame: { w: 300, h: 80 }, props: [color(), number("value", 60, 0, 100), bool("indeterminate")] },
  { is: "DitherMeter", label: "Meter", group: "display", frame: { w: 300, h: 80 }, props: [number("value", 65, 0, 100), number("min", 0), number("max", 100)] },
  { is: "DitherSpinner", label: "Spinner", group: "display", frame: { w: 120, h: 90 }, props: [color(), number("size", 24, 8, 96)] },
  { is: "DitherAurora", label: "Aurora", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67", "#5227FF"]), number("amplitude", 1, 0, 3, 0.1), number("blend", 0.5, 0, 1, 0.05), number("speed", 0.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherWaves", label: "Waves", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67"]), number("count", 14, 2, 40, 1), number("amplitude", 0.5, 0, 1.5, 0.05), number("frequency", 2, 0.5, 6, 0.1), number("speed", 0.5, 0, 3, 0.1), number("lineWidth", 0.18, 0.02, 0.5, 0.02), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), bool("mouseInteraction", true), number("mouseStrength", 0.6, 0, 2, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherSilk", label: "Silk", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67", "#5227FF"]), number("scale", 2, 0.4, 6, 0.1), number("speed", 0.5, 0, 3, 0.1), number("noiseIntensity", 1, 0, 3, 0.1), number("rotation", 0.6, 0, 3.14, 0.05), number("sharpness", 1.5, 0.5, 4, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherPlasma", label: "Plasma", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67", "#FFD23D"]), number("scale", 1, 0.3, 4, 0.1), number("speed", 0.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherLineWaves", label: "Line waves", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#3DA5FF", "#7CE0FF"]), number("count", 16, 2, 40, 1), number("amplitude", 0.5, 0, 1.5, 0.05), number("frequency", 2, 0.5, 8, 0.1), number("speed", 0.5, 0, 3, 0.1), number("lineWidth", 0.16, 0.02, 0.5, 0.02), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherThreads", label: "Threads", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67"]), number("count", 22, 2, 60, 1), number("amplitude", 0.6, 0, 1.5, 0.05), number("distortion", 2, 0.2, 6, 0.1), number("speed", 0.5, 0, 3, 0.1), number("lineWidth", 0.14, 0.02, 0.5, 0.02), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherDotGrid", label: "Dot grid", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67"]), number("gap", 26, 4, 80, 1), number("dotSize", 0.5, 0.1, 1, 0.05), number("speed", 0.5, 0, 3, 0.1), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), bool("mouseInteraction", true), number("mouseStrength", 1, 0, 3, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherRippleGrid", label: "Ripple grid", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#3DA5FF", "#7CE0FF", "#CFF6FF"]), number("gap", 26, 4, 80, 1), number("dotSize", 0.6, 0.1, 1, 0.05), number("frequency", 26, 4, 60, 1), number("speed", 0.5, 0, 3, 0.1), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherIridescence", label: "Iridescence", group: "display", frame: { w: 320, h: 220 }, props: [number("scale", 2, 0.4, 6, 0.1), number("speed", 0.5, 0, 3, 0.1), number("saturation", 0.85, 0, 1, 0.05), number("brightness", 0.9, 0, 1, 0.05), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherPixelSnow", label: "Pixel snow", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#CFF6FF", "#7CE0FF"]), number("density", 30, 6, 100, 1), number("speed", 0.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherBeams", label: "Beams", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67"]), number("count", 6, 1, 30, 1), number("angle", 0.6, 0, 3.14, 0.05), number("speed", 0.5, 0, 3, 0.1), number("sharpness", 3, 0.5, 8, 0.1), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherGridMotion", label: "Grid motion", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#3DA5FF", "#7CE0FF"]), number("count", 14, 2, 60, 1), number("angle", 0.5, 0, 6.28, 0.05), number("speed", 0.5, 0, 3, 0.1), number("lineWidth", 0.06, 0.01, 0.4, 0.01), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherGridScan", label: "Grid scan", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#27FF64", "#7CFF67"]), number("count", 16, 2, 60, 1), number("speed", 0.5, 0, 3, 0.1), number("lineWidth", 0.05, 0.01, 0.4, 0.01), number("scanWidth", 0.12, 0.02, 0.5, 0.02), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherGridDistortion", label: "Grid distortion", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67"]), number("count", 14, 2, 60, 1), number("distortion", 1, 0, 4, 0.1), number("speed", 0.5, 0, 3, 0.1), number("lineWidth", 0.06, 0.01, 0.4, 0.01), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), bool("mouseInteraction", true), number("mouseStrength", 1, 0, 3, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherLightRays", label: "Light rays", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#FFD23D", "#FF8A3D"]), number("rayCount", 16, 2, 60, 1), number("speed", 0.4, 0, 3, 0.1), number("spread", 1.2, 0, 4, 0.1), number("falloff", 0.7, 0, 2, 0.05), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherSideRays", label: "Side rays", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#3DA5FF", "#7CE0FF"]), select("side", "left", ["left", "right"]), number("rayCount", 12, 2, 60, 1), number("speed", 0.4, 0, 3, 0.1), number("spread", 1, 0, 4, 0.1), number("falloff", 0.6, 0, 2, 0.05), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherLightPillar", label: "Light pillar", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67"]), number("count", 8, 1, 40, 1), number("speed", 0.5, 0, 3, 0.1), number("width", 0.4, 0.05, 1, 0.05), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherSoftAurora", label: "Soft aurora", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67", "#A8FFB6"]), number("bands", 3, 1, 6, 1), number("amplitude", 1, 0, 3, 0.1), number("blend", 0.6, 0, 1, 0.05), number("speed", 0.4, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 0.5, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherDotField", label: "Dot field", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67"]), number("gap", 26, 4, 80, 1), number("speed", 0.5, 0, 3, 0.1), number("sizeVariation", 1, 0, 2, 0.1), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), bool("mouseInteraction", true), number("mouseStrength", 1, 0, 3, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherColorBends", label: "Color bends", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67", "#FFD23D"]), number("scale", 2, 0.4, 6, 0.1), number("bend", 0.4, 0, 1, 0.05), number("speed", 0.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherGradientBlinds", label: "Gradient blinds", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#FF3D2E", "#FFD23D"]), number("count", 8, 1, 40, 1), number("angle", 0.3, 0, 3.14, 0.05), number("speed", 0.5, 0, 3, 0.1), number("gap", 0.15, 0, 0.8, 0.05), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherGrainient", label: "Grainient", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67"]), number("angle", 0.6, 0, 6.28, 0.05), number("grain", 0.4, 0, 1, 0.05), number("speed", 0.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherDither", label: "Dither", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#7CFF67", "#5227FF"]), number("scale", 3, 0.5, 8, 0.1), number("speed", 0.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherFloatingLines", label: "Floating lines", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#3DA5FF", "#7CE0FF"]), number("count", 10, 1, 40, 1), number("amplitude", 1, 0, 3, 0.1), number("speed", 0.5, 0, 3, 0.1), number("lineWidth", 0.012, 0.004, 0.1, 0.002), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherPlasmaWave", label: "Plasma wave", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67", "#FFD23D"]), number("scale", 1, 0.3, 4, 0.1), number("speed", 0.5, 0, 3, 0.1), number("angle", 0.6, 0, 6.28, 0.05), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherRadar", label: "Radar", group: "display", frame: { w: 260, h: 260 }, props: [list("colors", ["#27FF64", "#7CFF67"]), number("rings", 4, 1, 12, 1), number("speed", 1, 0, 4, 0.1), number("sweepWidth", 0.6, 0.1, 3, 0.1), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherLetterGlitch", label: "Letter glitch", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#0A3A1A", "#27FF64", "#CFFFDF"]), number("columns", 24, 4, 80, 1), number("speed", 0.6, 0, 3, 0.1), number("trailLength", 0.5, 0.05, 1, 0.05), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherShapeGrid", label: "Shape grid", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67"]), number("gap", 18, 4, 60, 1), number("speed", 0.5, 0, 3, 0.1), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherLightning", label: "Lightning", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CE0FF", "#FFFFFF"]), number("bolts", 3, 1, 12, 1), number("speed", 0.5, 0, 3, 0.1), number("jitter", 0.3, 0, 1, 0.05), number("width", 0.03, 0.005, 0.2, 0.005), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherDarkVeil", label: "Dark veil", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#0A0A12", "#3A2A6A", "#5227FF"]), number("scale", 3, 0.4, 8, 0.1), number("speed", 0.4, 0, 3, 0.1), number("intensity", 2.5, 0, 5, 0.1), number("vignette", 0.7, 0, 1, 0.05), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherLiquidChrome", label: "Liquid chrome", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#1A1A22", "#8890A0", "#E8ECF4"]), number("scale", 2, 0.4, 6, 0.1), number("speed", 0.4, 0, 3, 0.1), number("distortion", 1, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherOrb", label: "Orb", group: "display", frame: { w: 260, h: 260 }, props: [list("colors", ["#5227FF", "#7CFF67", "#CFFFDF"]), number("size", 0.5, 0.1, 0.9, 0.05), number("speed", 0.5, 0, 3, 0.1), number("noiseAmount", 1, 0, 3, 0.1), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherPrism", label: "Prism", group: "display", frame: { w: 320, h: 220 }, props: [number("spread", 0.6, 0.1, 1.5, 0.05), number("speed", 0.5, 0, 3, 0.1), number("saturation", 0.9, 0, 1, 0.05), number("brightness", 1, 0, 1, 0.05), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherGalaxy", label: "Galaxy", group: "display", frame: { w: 260, h: 260 }, props: [list("colors", ["#3DA5FF", "#A8FFB6", "#FFFFFF"]), number("arms", 3, 1, 8, 1), number("twist", 8, 0, 30, 0.5), number("speed", 0.5, 0, 3, 0.1), number("density", 0.6, 0, 1, 0.05), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherBalatro", label: "Balatro", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#FF3D2E", "#FFD23D", "#27FF64"]), number("scale", 2, 0.4, 6, 0.1), number("speed", 0.5, 0, 3, 0.1), number("spin", 3, 0, 10, 0.1), number("contrast", 1, 0.2, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherBallpit", label: "Ballpit", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67", "#FF3D2E"]), number("count", 12, 3, 40, 1), number("speed", 0.5, 0, 3, 0.1), number("ballSize", 0.8, 0.3, 1.5, 0.05), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), bool("mouseInteraction", true), number("mouseStrength", 1, 0, 3, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherEvilEye", label: "Evil eye", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#0A0A0A", "#FF3D2E", "#FFD23D"]), number("size", 0.55, 0.2, 1, 0.05), number("speed", 0.5, 0, 3, 0.1), number("pupilSize", 0.4, 0.1, 0.9, 0.05), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), bool("mouseInteraction", true), number("mouseStrength", 1, 0, 3, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherHyperspeed", label: "Hyperspeed", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#3DA5FF", "#7CE0FF", "#FFFFFF"]), number("count", 24, 4, 80, 1), number("speed", 0.5, 0, 3, 0.1), number("streakLength", 0.5, 0.05, 1.2, 0.05), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherLightfall", label: "Lightfall", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CE0FF", "#CFFFFF"]), number("count", 16, 2, 60, 1), number("speed", 0.5, 0, 3, 0.1), number("trailLength", 0.6, 0.05, 1.4, 0.05), number("width", 0.06, 0.02, 0.3, 0.01), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherLiquidEther", label: "Liquid ether", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67", "#3DA5FF"]), number("scale", 2, 0.4, 6, 0.1), number("speed", 0.5, 0, 3, 0.1), number("flow", 1, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), bool("mouseInteraction", true), number("mouseStrength", 1, 0, 3, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherParticles", label: "Particles", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#3DA5FF", "#7CFF67", "#FFFFFF"]), number("count", 20, 4, 60, 1), number("speed", 0.5, 0, 3, 0.1), number("particleSize", 0.7, 0.1, 1, 0.05), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), bool("mouseInteraction", true), number("mouseStrength", 1, 0, 3, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherPixelBlast", label: "Pixel blast", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#FF3D2E", "#FFD23D"]), number("waves", 3, 1, 8, 1), number("speed", 0.5, 0, 3, 0.1), number("pixels", 40, 8, 120, 1), number("glow", 1.5, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherPrismaticBurst", label: "Prismatic burst", group: "display", frame: { w: 260, h: 260 }, props: [number("rays", 8, 1, 30, 1), number("speed", 0.5, 0, 3, 0.1), number("spread", 2, 0.2, 6, 0.1), number("saturation", 0.9, 0, 1, 0.05), number("brightness", 1, 0, 1, 0.05), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherFaultyTerminal", label: "Faulty terminal", group: "display", frame: { w: 320, h: 200 }, props: [{ ...color("#ffffff"), key: "tint" }, number("scale", 1.5, 0.2, 4, 0.1), number("digitSize", 1.2, 0.5, 3, 0.1), number("scanlineIntensity", 1, 0, 2, 0.1), number("glitchAmount", 1, 0, 3, 0.1), number("flickerAmount", 1, 0, 2, 0.1), number("noiseAmp", 1, 0, 2, 0.1), number("chromaticAberration", 0, 0, 8, 1), number("curvature", 0, 0, 1, 0.05), number("dither", 0, 0, 1, 0.1), number("brightness", 1, 0, 2, 0.1), number("timeScale", 1, 0, 3, 0.1), bool("mouseReact", true), number("mouseStrength", 0.5, 0, 2, 0.1), bool("pageLoadAnimation"), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("pause")] },
  { is: "DitherFerrofluid", label: "Ferrofluid", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#27FF64", "#7CFF67", "#A8FFB6"]), number("speed", 0.5, 0, 3, 0.1), number("scale", 1.6, 0.4, 4, 0.1), number("turbulence", 1, 0, 3, 0.1), number("fluidity", 0.1, 0, 1, 0.05), number("rimWidth", 0.2, 0.02, 0.6, 0.02), number("sharpness", 2.5, 0.5, 6, 0.1), number("shimmer", 1.5, 0, 3, 0.1), number("glow", 2, 0, 4, 0.1), select("flowDirection", "down", ["up", "down", "left", "right"]), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.1), bool("mouseInteraction", true), number("mouseStrength", 1, 0, 3, 0.1), number("mouseRadius", 0.35, 0.05, 1, 0.05), number("mouseDampening", 0.15, 0, 1, 0.05), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherSkeleton", label: "Skeleton", group: "display", frame: { w: 300, h: 100 }, props: [] },
  { is: "DitherSeparator", label: "Separator", group: "display", frame: { w: 260, h: 60 }, props: [select("orientation", "horizontal", ["horizontal", "vertical"])] },
  { is: "DitherTooltip", label: "Tooltip", group: "overlays", frame: { w: 220, h: 100 }, props: [text("text", "Helpful detail"), number("delay", 0, 0, 1000)], slotText: "Hover or focus" },
  { is: "DitherPreviewCard", label: "Preview card", group: "overlays", frame: { w: 300, h: 180 }, props: [number("delay", 0, 0, 1000)], slotText: "Preview details", demo: "preview-card" },

  { is: "DitherMenu", label: "Menu", group: "overlays", frame: { w: 220, h: 180 }, props: [list("items", ["Copy", "Paste", "Delete"])], slotText: "Open menu", mapProps: (p) => ({ ...p, items: items(p.items) }) },
  { is: "DitherContextMenu", label: "Context menu", group: "overlays", frame: { w: 260, h: 140 }, props: [list("items", ["Copy", "Paste", "Delete"])], slotText: "Right-click this area", mapProps: (p) => ({ ...p, items: items(p.items) }) },
  { is: "DitherMenubar", label: "Menubar", group: "overlays", frame: { w: 360, h: 100 }, props: [list("menus", ["File", "Edit", "View"])], mapProps: (p) => ({ ...p, menus: strList(p.menus).map((label) => ({ label, items: [{ label: "Open" }, { label: "Settings" }] })) }) },
  { is: "DitherPopover", label: "Popover", group: "overlays", frame: { w: 280, h: 180 }, props: [select("align", "start", ["start", "center", "end"])], slotText: "Popover content", vmodel: { def: false, prop: "open", event: "close" }, demo: "popover" },
  { is: "DitherDialog", label: "Dialog", group: "overlays", frame: { w: 300, h: 150 }, props: [text("title", "Dialog title")], slotText: "Dialog content", vmodel: { def: false, prop: "open", event: "close" }, demo: "dialog" },
  { is: "DitherCenterMorphModal", label: "Center morph modal", group: "overlays", frame: { w: 300, h: 150 }, props: [text("label", "Release notes")], slotText: "The surface unfolds from its exact center.", vmodel: { def: false, prop: "open", event: "close" }, demo: "dialog" },
  { is: "DitherCommand", label: "Command", group: "overlays", frame: { w: 320, h: 150 }, props: [text("placeholder", "Type a command…"), list("items", ["New artboard", "Export image", "Toggle theme", "Open settings"])], vmodel: { def: false, prop: "open", event: "close" }, demo: "dialog", mapProps: (p) => ({ ...p, items: strList(p.items).map((label) => ({ value: label.toLowerCase(), label })) }) },
  { is: "DitherAlertDialog", label: "Alert dialog", group: "overlays", frame: { w: 300, h: 150 }, props: [text("title", "Delete item?"), text("description", "This action cannot be undone."), text("confirmLabel", "Delete"), text("cancelLabel", "Cancel"), bool("danger", true)], vmodel: { def: false, prop: "open", event: "cancel" }, demo: "alert" },
  { is: "DitherDrawer", label: "Drawer", group: "overlays", frame: { w: 300, h: 160 }, props: [select("side", "right", ["right", "left", "bottom"]), text("title", "Drawer"), bool("swipe", true), bool("modal", true), bool("dismissible", true)], slotText: "Drawer content", vmodel: { def: false, prop: "open", event: "close" }, demo: "drawer" },
  { is: "DitherSwipeArea", label: "Swipe area", group: "overlays", frame: { w: 300, h: 150 }, props: [select("side", "right", ["right", "left", "bottom"]), number("size", 24, 8, 64), number("threshold", 24, 8, 100), bool("disabled")], vmodel: { def: false }, demo: "swipe-area" },
  { is: "DitherToaster", label: "Toaster", group: "overlays", frame: { w: 260, h: 130 }, props: [color(), text("message", "Saved to project")], demo: "toaster" },

  { is: "DitherField", label: "Field", group: "structure", frame: { w: 300, h: 150 }, props: [text("label", "Email"), text("description", "We will never share it."), text("error", "")], demo: "field" },
  { is: "DitherFieldset", label: "Fieldset", group: "structure", frame: { w: 340, h: 190 }, props: [text("legend", "Account")], demo: "fieldset" },
  { is: "DitherForm", label: "Form", group: "structure", frame: { w: 340, h: 220 }, props: [], demo: "form" },
  { is: "DitherScrollArea", label: "Scroll area", group: "structure", frame: { w: 280, h: 200 }, props: [], slotText: "Scrollable content" },
  { is: "DitherShell", label: "Shell", group: "structure", frame: { w: 360, h: 260 }, props: [bool("frame", true)], slotText: "Content" },
  { is: "DitherRail", label: "Rail", group: "structure", frame: { w: 220, h: 300 }, props: [text("label", "Rail"), select("side", "left", ["left", "right"])], demo: "sidebar" },
  { is: "DitherConsole", label: "Console", group: "structure", frame: { w: 340, h: 220 }, props: [text("title", "console"), list("lines", ["$ vite build", "transforming…", "built in 4.2s"]), bool("follow", true), bool("caret", true)] },
  { is: "DitherCanvas", label: "Canvas", group: "structure", frame: { w: 320, h: 220 }, props: [select("pattern", "dots", ["dots", "grid", "plain"]), number("cell", 16, 4, 64)], slotText: "Work surface" },
  { is: "DitherGrid", label: "Grid", group: "structure", frame: { w: 340, h: 220 }, props: [number("min", 120, 80, 400), text("gap", "0.75rem")], slotText: "Card" },
  { is: "DitherToolbar", label: "Toolbar", group: "structure", frame: { w: 360, h: 100 }, props: [text("label", "Formatting")], demo: "toolbar" },
  { is: "DitherSidebar", label: "Sidebar", group: "structure", frame: { w: 300, h: 420 }, props: [text("label", "Project"), select("variant", "default", ["default", "floating", "inset", "washed"]), select("side", "left", ["left", "right"]), select("collapse", "rail", ["rail", "hide", "none"]), select("density", "default", ["default", "compact"]), bool("toggle", true), { ...color(), key: "washColor" }], vmodel: { def: false }, demo: "sidebar" },
  { is: "DitherSidebarItem", label: "Sidebar item", group: "structure", frame: { w: 300, h: 240 }, props: [text("label", "Dashboard"), bool("active", true), color(), text("badge", "3")], demo: "sidebar" },
  { is: "DitherSidebarGroup", label: "Sidebar group", group: "structure", frame: { w: 300, h: 260 }, props: [text("label", "Workspace")], demo: "sidebar" },
  { is: "DitherSidebarSub", label: "Sidebar sub", group: "structure", frame: { w: 300, h: 280 }, props: [text("label", "Projects")], vmodel: { def: true }, demo: "sidebar" },
  { is: "DitherDrawerIndent", label: "Drawer indent", group: "structure", frame: { w: 320, h: 180 }, props: [], slotText: "Indented application surface", vmodel: { def: false }, demo: "drawer-indent" },

  { is: "DitherGradientText", label: "Gradient text", group: "display", frame: { w: 320, h: 100 }, props: [list("colors", ["#358ff3", "#7CFF67", "#358ff3"]), number("speed", 1, 0, 4, 0.1)], slotText: "Gradient text" },
  { is: "DitherShinyText", label: "Shiny text", group: "display", frame: { w: 320, h: 100 }, props: [number("speed", 1, 0, 4, 0.1), bool("disabled")], slotText: "Shiny text" },
  { is: "DitherGlitchText", label: "Glitch text", group: "display", frame: { w: 320, h: 100 }, props: [text("text", "GLITCH"), number("speed", 1, 0, 4, 0.1)] },
  { is: "DitherSplitText", label: "Split text", group: "display", frame: { w: 320, h: 100 }, props: [text("text", "Split text"), number("stagger", 40, 0, 200, 5), number("duration", 600, 100, 2000, 50)] },
  { is: "DitherRotatingText", label: "Rotating text", group: "display", frame: { w: 320, h: 100 }, props: [list("texts", ["Vue", "canvas", "dither"]), number("interval", 2000, 400, 6000, 100)], mapProps: (p) => ({ ...p, texts: strList(p.texts) }) },
  { is: "DitherCountUp", label: "Count up", group: "display", frame: { w: 220, h: 100 }, props: [number("to", 1984, 0, 1000000, 1), number("from", 0, 0, 1000000, 1), number("duration", 1500, 100, 5000, 100), number("decimals", 0, 0, 4, 1)] },
  { is: "DitherNumberFlow", label: "Number flow", group: "display", frame: { w: 220, h: 100 }, props: [number("value", 12480, 0, 1000000, 1), number("decimals", 0, 0, 4, 1), number("duration", 600, 100, 2000, 50)] },
  { is: "DitherExpandTabs", label: "Expand tabs", group: "display", frame: { w: 320, h: 90 }, props: [list("tabs", ["Home", "Library", "Alerts"]), color()], vmodel: { def: "home" }, mapProps: (p) => ({ ...p, tabs: strList(p.tabs).map((label) => ({ value: label.toLowerCase(), label })) }) },
  { is: "DitherIsland", label: "Island", group: "display", frame: { w: 280, h: 140 }, props: [text("label", "Deploy running"), color(), bool("live", true)], vmodel: { def: false }, slotText: "Build 214 — 3 of 5 steps done." },
  { is: "DitherCardStack", label: "Card stack", group: "display", frame: { w: 300, h: 200 }, props: [list("items", ["Prints", "Frames", "Zines"]), number("depth", 2, 1, 4, 1)] },
  { is: "DitherScrollProgress", label: "Scroll progress", group: "display", frame: { w: 320, h: 60 }, props: [select("attach", "parent", ["viewport", "parent"]), select("edge", "top", ["top", "bottom"]), color()] },
  { is: "DitherDock", label: "Dock", group: "display", frame: { w: 340, h: 110 }, props: [list("items", ["Home", "Studio", "Docs", "Alerts"]), number("magnify", 1.7, 1, 3, 0.1), number("range", 80, 30, 200, 10)], mapProps: (p) => ({ ...p, items: strList(p.items).map((label) => ({ value: label.toLowerCase(), label })) }) },
  { is: "DitherPreviewRail", label: "Preview rail", group: "display", frame: { w: 240, h: 200 }, props: [list("items", ["Home", "Studio", "Docs", "Alerts"]), number("range", 56, 24, 160, 4), select("side", "left", ["left", "right"])], vmodel: { def: "home" }, mapProps: (p) => ({ ...p, items: strList(p.items).map((label) => ({ value: label.toLowerCase(), label })) }) },
  { is: "DitherVideoPlayer", label: "Video player", group: "display", frame: { w: 360, h: 280 }, props: [text("src", ""), text("label", "Video"), color()] },
  { is: "DitherBracket", label: "Bracket", group: "display", frame: { w: 420, h: 260 }, props: [list("teams", ["Bayer", "Ordered", "Halftone", "Threshold"]), color(), bool("interactive", false)], mapProps: (p) => { const t = strList(p.teams); const rounds = [] as { a: string; b: string }[][]; const first = [] as { a: string; b: string }[]; for (let i = 0; i + 1 < t.length; i += 2) first.push({ a: t[i], b: t[i + 1] }); rounds.push(first); let n = first.length; while (n > 1) { rounds.push(Array.from({ length: Math.floor(n / 2) }, () => ({ a: "—", b: "—" }))); n = Math.floor(n / 2) } const { teams: _teams, ...rest } = p; return { ...rest, rounds } } },
  { is: "DitherSchedule", label: "Schedule", group: "display", frame: { w: 340, h: 280 }, props: [list("slots", ["9|10.5|Standup", "11|12.5|Design review", "14|16|Focus block"]), number("from", 8, 0, 23, 1), number("to", 18, 1, 24, 1), number("now", 13.5, 0, 24, 0.5)], mapProps: (p) => { const colors = ["blue", "purple", "green", "orange"]; const events = strList(p.slots).map((s, i) => { const [start, end, label] = s.split("|"); return { start: Number(start) || 9, end: Number(end) || 10, label: label ?? "Event", color: colors[i % colors.length] } }); const { slots: _slots, ...rest } = p; return { ...rest, events } } },
  { is: "DitherInfiniteCanvas", label: "Infinite canvas", group: "structure", frame: { w: 360, h: 260 }, props: [select("pattern", "dots", ["dots", "grid", "plain"]), number("cell", 16, 4, 64), number("minZoom", 0.25, 0.1, 1, 0.05), number("maxZoom", 3, 1, 8, 0.5)], slotText: "Drag to pan · wheel to zoom" },
  { is: "DitherSnapButton", label: "Snap button", group: "display", frame: { w: 260, h: 110 }, props: [number("threshold", 64, 24, 200, 4), select("axis", "x", ["x", "y", "both"]), color(), bool("disabled")], slotText: "Pull to confirm" },
  { is: "DitherGooeyMenu", label: "Gooey menu", group: "display", frame: { w: 220, h: 280 }, props: [list("items", ["Add", "Export", "Share"]), select("direction", "up", ["up", "down", "left", "right"]), number("spacing", 52, 32, 100, 4)], vmodel: { def: false }, mapProps: (p) => ({ ...p, items: strList(p.items).map((label) => ({ value: label.toLowerCase(), label })) }) },
  { is: "DitherBlurText", label: "Blur text", group: "display", frame: { w: 340, h: 100 }, props: [text("text", "Blur into focus"), select("by", "words", ["words", "chars"]), number("stagger", 90, 0, 400, 10), number("duration", 600, 100, 2000, 50)] },
  { is: "DitherDecryptedText", label: "Decrypted text", group: "display", frame: { w: 300, h: 100 }, props: [text("text", "DECRYPTED"), number("speed", 1, 0.2, 4, 0.1), select("trigger", "view", ["view", "hover"])] },
  { is: "DitherScrambleText", label: "Scramble text", group: "display", frame: { w: 340, h: 100 }, props: [text("text", "Hover to scramble"), number("speed", 1, 0.2, 4, 0.1)] },
  { is: "DitherShuffle", label: "Shuffle", group: "display", frame: { w: 300, h: 100 }, props: [text("text", "Shuffle in"), number("stagger", 55, 0, 200, 5), number("duration", 650, 100, 2000, 50)] },
  { is: "DitherTextType", label: "Text type", group: "display", frame: { w: 340, h: 100 }, props: [list("texts", ["Type this out.", "Then this."]), number("typingSpeed", 60, 10, 300, 5), number("deletingSpeed", 35, 10, 300, 5), number("pause", 1400, 200, 5000, 100), bool("loop", true), bool("cursor", true)], mapProps: (p) => ({ ...p, texts: strList(p.texts) }) },
  { is: "DitherFallingText", label: "Falling text", group: "display", frame: { w: 300, h: 100 }, props: [text("text", "Falling text"), number("stagger", 45, 0, 200, 5), number("duration", 700, 100, 2000, 50)] },
  { is: "DitherScrollReveal", label: "Scroll reveal", group: "display", frame: { w: 360, h: 120 }, props: [text("text", "Words reveal as you scroll into view")] },
  { is: "DitherScrollFloat", label: "Scroll float", group: "display", frame: { w: 320, h: 100 }, props: [text("text", "Scroll float"), number("amount", 1, 0, 3, 0.1)] },
  { is: "DitherScrollVelocity", label: "Scroll velocity", group: "display", frame: { w: 380, h: 80 }, props: [text("text", "DITHER · UI · TOOLKIT · "), number("baseSpeed", 60, 0, 400, 10)] },
  { is: "DitherTextCursor", label: "Text cursor", group: "display", frame: { w: 280, h: 160 }, props: [text("text", "dither")] },
  { is: "DitherTextPressure", label: "Text pressure", group: "display", frame: { w: 300, h: 100 }, props: [text("text", "Pressure"), number("radius", 140, 20, 400, 10), number("strength", 1, 0, 3, 0.1)] },
  { is: "DitherVariableProximity", label: "Variable proximity", group: "display", frame: { w: 400, h: 120 }, props: [text("text", "Move the cursor across this line to feel the weight shift"), number("radius", 120, 20, 400, 10)] },
  { is: "DitherTrueFocus", label: "True focus", group: "display", frame: { w: 320, h: 100 }, props: [text("text", "True focus mode"), number("interval", 1400, 300, 5000, 100), number("blur", 5, 0, 12, 0.5)] },
  { is: "DitherCircularText", label: "Circular text", group: "display", frame: { w: 190, h: 190 }, props: [text("text", "DITHER · UI · TOOLKIT · "), number("duration", 12, 2, 60, 1), number("size", 170, 80, 400, 10)] },
  { is: "DitherCurvedLoop", label: "Curved loop", group: "display", frame: { w: 420, h: 120 }, props: [text("text", "DITHER UI · CANVAS + BAYER · "), number("speed", 60, 0, 300, 10)] },
  { is: "DitherFuzzyText", label: "Fuzzy text", group: "display", frame: { w: 240, h: 100 }, props: [text("text", "FUZZY"), number("intensity", 4, 0, 20, 0.5)] },
  { is: "DitherAsciiText", label: "ASCII text", group: "display", frame: { w: 320, h: 150 }, props: [text("text", "DITHER"), number("cols", 64, 8, 160, 4)] },
  { is: "DitherAnimatedContent", label: "Animated content", group: "display", frame: { w: 260, h: 120 }, props: [number("distance", 40, 0, 200, 5), select("direction", "vertical", ["vertical", "horizontal"]), bool("reverse"), number("duration", 800, 100, 3000, 50), number("delay", 0, 0, 2000, 50)], slotText: "Animated content" },
  { is: "DitherFadeContent", label: "Fade content", group: "display", frame: { w: 260, h: 120 }, props: [number("duration", 1000, 100, 3000, 50), number("delay", 0, 0, 2000, 50), bool("blur")], slotText: "Fade content" },
  { is: "DitherGradualBlur", label: "Gradual blur", group: "display", frame: { w: 280, h: 160 }, props: [select("position", "bottom", ["bottom", "top"]), number("height", 96, 16, 300, 4), number("strength", 4, 0, 20, 0.5)], slotText: "Content fades into a soft edge as it reaches the blur band" },
  { is: "DitherStarBorder", label: "Star border", group: "display", frame: { w: 220, h: 90 }, props: [color("green"), number("speed", 6, 1, 20, 0.5), number("thickness", 1, 1, 6, 1)], slotText: "Star border" },
  { is: "DitherElectricBorder", label: "Electric border", group: "display", frame: { w: 220, h: 90 }, props: [color(), number("speed", 1, 0.2, 4, 0.1), number("thickness", 2, 1, 6, 1)], slotText: "Electric border" },
  { is: "DitherGlareHover", label: "Glare hover", group: "display", frame: { w: 240, h: 140 }, props: [], slotText: "Hover for a glare sweep" },
  { is: "DitherMagnet", label: "Magnet", group: "display", frame: { w: 220, h: 120 }, props: [number("strength", 0.4, 0, 1, 0.05), number("radius", 200, 40, 500, 10)], slotText: "Magnet" },
  { is: "DitherClickSpark", label: "Click spark", group: "display", frame: { w: 240, h: 140 }, props: [color(), number("count", 8, 3, 20, 1), number("size", 16, 4, 60, 2), number("duration", 420, 100, 1500, 20)], slotText: "Click anywhere here" },
  { is: "DitherBlobCursor", label: "Blob cursor", group: "display", frame: { w: 240, h: 160 }, props: [color(), number("size", 48, 8, 160, 4), number("lag", 0.18, 0.02, 1, 0.02)], slotText: "Move your cursor here" },
  { is: "DitherCrosshair", label: "Crosshair", group: "display", frame: { w: 240, h: 160 }, props: [color(), number("thickness", 1, 1, 6, 1)], slotText: "Move your cursor here" },
  { is: "DitherGhostCursor", label: "Ghost cursor", group: "display", frame: { w: 240, h: 160 }, props: [color(), number("count", 18, 4, 60, 1), number("size", 10, 2, 40, 1)], slotText: "Move your cursor here" },
  { is: "DitherSplashCursor", label: "Splash cursor", group: "display", frame: { w: 240, h: 160 }, props: [color("blue"), number("maxRadius", 60, 10, 200, 5), number("duration", 700, 100, 2000, 50)], slotText: "Move your cursor here" },
  { is: "DitherTargetCursor", label: "Target cursor", group: "display", frame: { w: 240, h: 160 }, props: [color(), number("size", 36, 12, 120, 4)], slotText: "Move your cursor here" },
  { is: "DitherPixelTrail", label: "Pixel trail", group: "display", frame: { w: 240, h: 160 }, props: [color(), number("gap", 24, 8, 80, 2)], slotText: "Move your cursor here" },
  { is: "DitherImageTrail", label: "Image trail", group: "display", frame: { w: 260, h: 180 }, props: [list("colors", ["#5227FF", "#7CFF67", "#3DA5FF", "#FF3D2E", "#FFD23D"]), number("size", 40, 8, 120, 4), number("duration", 650, 100, 2000, 50)], slotText: "Move your cursor here" },
  { is: "DitherMetaBalls", label: "Meta balls", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67", "#3DA5FF"]), number("count", 6, 1, 16, 1), number("speed", 1, 0, 4, 0.1), number("ballSize", 1, 0.3, 3, 0.1), number("glow", 1.5, 0.2, 4, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.05), bool("mouseInteraction", true), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherMetallicPaint", label: "Metallic paint", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#1A1A22", "#8890A0", "#E8ECF4"]), number("scale", 3, 0.5, 8, 0.5), number("speed", 0.4, 0, 3, 0.1), number("distortion", 0.6, 0, 2, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.05), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherNoise", label: "Noise", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#3DA5FF", "#7CE0FF", "#FFFFFF"]), number("speed", 1, 0, 4, 0.1), number("density", 0.5, 0, 1, 0.05), number("opacity", 1, 0, 1, 0.05), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherCubes", label: "Cubes", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67", "#CFFFDF"]), number("scale", 6, 1, 16, 1), number("speed", 0.4, 0, 3, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.05), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherRibbons", label: "Ribbons", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67", "#3DA5FF"]), number("count", 5, 1, 16, 1), number("speed", 0.5, 0, 3, 0.1), number("thickness", 0.12, 0.02, 0.4, 0.01), number("amplitude", 1, 0, 3, 0.1), number("glow", 1.2, 0.2, 4, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.05), bool("mouseInteraction", true), number("mouseStrength", 1, 0, 3, 0.1), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherShapeBlur", label: "Shape blur", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CFF67"]), number("size", 0.4, 0.1, 1, 0.05), number("speed", 0.6, 0, 3, 0.1), number("softness", 0.3, 0.05, 1, 0.05), number("opacity", 1, 0, 1, 0.05), number("dither", 0.6, 0, 1, 0.05), bool("mouseInteraction", true), number("mouseStrength", 0.5, 0, 1, 0.05), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherStrands", label: "Strands", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#5227FF", "#7CE0FF"]), number("count", 40, 4, 120, 2), number("speed", 0.4, 0, 3, 0.1), number("sway", 0.15, 0, 0.5, 0.01), number("lineWidth", 0.01, 0.002, 0.05, 0.002), number("glow", 1, 0.2, 4, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.05), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherLaserFlow", label: "Laser flow", group: "display", frame: { w: 320, h: 220 }, props: [list("colors", ["#FF3D2E", "#FFD23D", "#FFFFFF"]), number("count", 4, 1, 12, 1), number("speed", 0.6, 0, 3, 0.1), number("beamWidth", 0.02, 0.005, 0.1, 0.005), number("glow", 1, 0.2, 4, 0.1), number("opacity", 1, 0, 1, 0.05), number("dither", 1, 0, 1, 0.05), select("mixBlendMode", "normal", ["normal", "screen", "lighten", "plus-lighter"]), bool("paused")] },
  { is: "DitherAntigravity", label: "Antigravity", group: "display", frame: { w: 280, h: 200 }, props: [color("green"), number("count", 40, 4, 160, 4), number("speed", 1, 0, 4, 0.1)], slotText: "Antigravity" },
  { is: "DitherLogoLoop", label: "Logo loop", group: "display", frame: { w: 360, h: 70 }, props: [list("items", ["DITHER", "BAYER", "CANVAS", "VUE", "PIXELS"]), number("speed", 18, 3, 60, 1), number("gap", 48, 8, 160, 4)] },
  { is: "DitherMagicRings", label: "Magic rings", group: "display", frame: { w: 240, h: 200 }, props: [color("green"), number("count", 4, 1, 10, 1), number("duration", 3, 0.5, 10, 0.5)], slotText: "Magic" },
  { is: "DitherMagnetLines", label: "Magnet lines", group: "display", frame: { w: 280, h: 200 }, props: [color("green"), number("gap", 28, 12, 80, 2), number("lineLength", 14, 4, 40, 2)], slotText: "" },
  { is: "DitherOrbitImages", label: "Orbit images", group: "display", frame: { w: 220, h: 220 }, props: [list("items", ["A", "B", "C", "D", "E"]), number("radius", 80, 20, 200, 5), number("duration", 16, 2, 60, 1), number("size", 200, 80, 400, 10)] },
  { is: "DitherPixelTransition", label: "Pixel transition", group: "display", frame: { w: 260, h: 160 }, props: [number("rows", 6, 2, 20, 1), number("cols", 10, 2, 30, 1), color()], slotText: "Hover to reveal" },
  { is: "DitherStickerPeel", label: "Sticker peel", group: "display", frame: { w: 200, h: 120 }, props: [], slotText: "Peel me" },
]

export const componentEntry = (is: string): ComponentEntry | undefined =>
  COMPONENT_REGISTRY.find((e) => e.is === is)

export function defaultComponentProps(entry: ComponentEntry): Record<string, unknown> {
  return Object.fromEntries(entry.props.map((p) => [p.key, p.def]))
}

const isPlain = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null && !Array.isArray(v)

export function sanitizeComponentProps(entry: ComponentEntry, raw: unknown): Record<string, unknown> {
  const src = isPlain(raw) ? raw : {}
  const out: Record<string, unknown> = {}
  for (const spec of entry.props) {
    const v = src[spec.key]
    switch (spec.kind) {
      case "text":
        out[spec.key] = typeof v === "string" ? v : spec.def
        break
      case "boolean":
        out[spec.key] = typeof v === "boolean" ? v : spec.def
        break
      case "number": {
        let n = typeof v === "number" && Number.isFinite(v) ? v : spec.def
        if (spec.min != null) n = Math.max(spec.min, n)
        if (spec.max != null) n = Math.min(spec.max, n)
        out[spec.key] = n
        break
      }
      case "select":
        out[spec.key] = spec.options.includes(v as string) ? v : spec.def
        break
      case "color":
        out[spec.key] = typeof v === "string" || typeof v === "number" ? v : spec.def
        break
      case "list":
        out[spec.key] = Array.isArray(v) ? v.filter((x): x is string => typeof x === "string") : [...spec.def]
        break
    }
  }
  return out
}
