export const BACKGROUNDS_NAV = [
  { id: "aurora", label: "Aurora" },
  { id: "waves", label: "Waves" },
  { id: "line-waves", label: "Line waves" },
  { id: "threads", label: "Threads" },
  { id: "silk", label: "Silk" },
  { id: "plasma", label: "Plasma" },
  { id: "iridescence", label: "Iridescence" },
  { id: "dot-grid", label: "Dot grid" },
  { id: "ripple-grid", label: "Ripple grid" },
  { id: "pixel-snow", label: "Pixel snow" },
  { id: "beams", label: "Beams" },
  { id: "light-rays", label: "Light rays" },
  { id: "side-rays", label: "Side rays" },
  { id: "light-pillar", label: "Light pillar" },
  { id: "soft-aurora", label: "Soft aurora" },
  { id: "grid-motion", label: "Grid motion" },
  { id: "grid-scan", label: "Grid scan" },
  { id: "grid-distortion", label: "Grid distortion" },
  { id: "dot-field", label: "Dot field" },
  { id: "color-bends", label: "Color bends" },
  { id: "gradient-blinds", label: "Gradient blinds" },
  { id: "grainient", label: "Grainient" },
  { id: "plasma-wave", label: "Plasma wave" },
  { id: "floating-lines", label: "Floating lines" },
  { id: "radar-sweep", label: "Radar" },
  { id: "dither", label: "Dither" },
  { id: "faulty-terminal", label: "Faulty terminal" },
  { id: "ferrofluid", label: "Ferrofluid" },
]
