export const ANIMATIONS_NAV = [
  { id: "animated-content", label: "Animated content" },
  { id: "fade-content", label: "Fade content" },
  { id: "gradual-blur", label: "Gradual blur" },
  { id: "star-border", label: "Star border" },
  { id: "electric-border", label: "Electric border" },
  { id: "glare-hover", label: "Glare hover" },
  { id: "magnet", label: "Magnet" },
  { id: "click-spark", label: "Click spark" },
  { id: "blob-cursor", label: "Blob cursor" },
  { id: "crosshair", label: "Crosshair" },
  { id: "ghost-cursor", label: "Ghost cursor" },
  { id: "splash-cursor", label: "Splash cursor" },
  { id: "target-cursor", label: "Target cursor" },
  { id: "pixel-trail", label: "Pixel trail" },
  { id: "image-trail", label: "Image trail" },
  { id: "meta-balls", label: "Meta balls" },
  { id: "metallic-paint", label: "Metallic paint" },
  { id: "noise", label: "Noise" },
  { id: "cubes", label: "Cubes" },
  { id: "ribbons", label: "Ribbons" },
  { id: "shape-blur", label: "Shape blur" },
  { id: "strands", label: "Strands" },
  { id: "laser-flow", label: "Laser flow" },
  { id: "antigravity", label: "Antigravity" },
  { id: "logo-loop", label: "Logo loop" },
  { id: "magic-rings", label: "Magic rings" },
  { id: "magnet-lines", label: "Magnet lines" },
  { id: "orbit-images", label: "Orbit images" },
  { id: "pixel-transition", label: "Pixel transition" },
  { id: "sticker-peel", label: "Sticker peel" },
  { id: "expand-tabs", label: "Expand tabs" },
  { id: "island", label: "Island" },
  { id: "card-stack", label: "Card stack" },
  { id: "dock", label: "Dock" },
  { id: "preview-rail", label: "Preview rail" },
  { id: "scroll-progress", label: "Scroll progress" },
  { id: "snap-button", label: "Snap button" },
  { id: "gooey-menu", label: "Gooey menu" },
  { id: "bouncy-accordion", label: "Bouncy accordion" },
  { id: "expanding-arrow", label: "Expanding arrow" },
  { id: "slide-action", label: "Slide action" },
  { id: "hold-action", label: "Hold action" },
]
