export const ANIMATIONS_NAV = [
  { id: "animated-content", label: "Animated content" },
  { id: "fade-content", label: "Fade content" },
  { id: "gradual-blur", label: "Gradual blur" },
  { id: "star-border", label: "Star border" },
  { id: "electric-border", label: "Electric border" },
  { id: "glare-hover", label: "Glare hover" },
  { id: "magnet", label: "Magnet" },
  { id: "click-spark", label: "Click spark" },
  { id: "blob-cursor", label: "Blob cursor" },
  { id: "crosshair", label: "Crosshair" },
  { id: "ghost-cursor", label: "Ghost cursor" },
  { id: "splash-cursor", label: "Splash cursor" },
  { id: "target-cursor", label: "Target cursor" },
  { id: "pixel-trail", label: "Pixel trail" },
  { id: "image-trail", label: "Image trail" },
  { id: "meta-balls", label: "Meta balls" },
  { id: "metallic-paint", label: "Metallic paint" },
  { id: "noise", label: "Noise" },
  { id: "cubes", label: "Cubes" },
  { id: "ribbons", label: "Ribbons" },
  { id: "shape-blur", label: "Shape blur" },
  { id: "strands", label: "Strands" },
  { id: "laser-flow", label: "Laser flow" },
]
